name: 'foundry-toolchain'
description: 'Install Foundry with enhanced caching and gas snapshot tracking'
author: 'Foundry'
branding:
  color: 'gray-dark'
  icon: 'play-circle'

inputs:
  cache:
    default: 'true'
    description: |
      Whether to enable caching for RPC responses and artifacts.

      Caching is activated by default.
    required: false
  cache-key:
    default: '${{ github.job }}-${{ github.sha }}'
    description: |
      A custom cache key to use.

      This key is used to identify the cache. If not provided, a default key consisting of the job id and the commit hash is used.
    required: false
  cache-restore-keys:
    default: |-
      ${{ github.job }}-
    description: |
      Custom cache restore keys to use.

      This key is used to identify the cache to restore. If not provided, a default key consisting of the job id is used.
    required: false
  version:
    default: 'stable'
    description: |
      Foundry version.

      This version number has to match a released version of Foundry.
      The default value is `stable`, which will pull the latest stable build.
    required: false
  gas-snapshot:
    default: 'false'
    description: |
      Whether to enable gas snapshot tracking.

      When enabled, the action will capture gas snapshots from Forge tests and track them over time.
    required: false
  gas-snapshot-test-pattern:
    default: ''
    description: |
      Test pattern to use for gas snapshots.

      This pattern is passed to the `--match-test` option of the `forge snapshot` command.
      If not provided, all tests will be included in the gas snapshot.
    required: false
  gas-snapshot-pr-comment:
    default: 'true'
    description: |
      Whether to post gas snapshot comparison as a comment on pull requests.

      When enabled and running on a pull request, the action will post a comment with the gas snapshot comparison.
    required: false
  github-token:
    default: '${{ github.token }}'
    description: |
      GitHub token to use for API operations.

      This token is used for posting comments on pull requests and other GitHub API operations.
      If not provided, the default GitHub token will be used.
    required: false

runs:
  using: 'node20'
  main: 'dist/index.js'
  post: 'dist/save/index.js'
  post-if: success()
